#ifndef DRIVERS_UART_UART_DEFS_H
#define DRIVERS_UART_UART_DEFS_H 1

#define UART_DATA 0
#define UART_INTERRUPT 1
#define UART_INTERRUPT_IDENTIFACTOR 2
#define UART_LINE_CONTROL 3
#define UART_MODEM_CONTROL 4
#define UART_LINE_STATUS 5
#define UART_MODEM_STATUS 6
#define UART_SCRATCH 7

#define UART_BAUD_RATE_LOW UART_DATA
#define UART_BAUD_RATE_HIGH UART_INTERRUPT
#define UART_FIFO_CONTROLLER UART_INTERRUPT_IDENTIFACTOR

#define UART_LINE_DS_5 0
#define UART_LINE_DS_6 1
#define UART_LINE_DS_7 2
#define UART_LINE_DS_8 3
#define UART_LINE_DLAB_STATUS (1 << 7)

#define UART_MODEM_DTR (1 << 0)
#define UART_MODEM_RTS (1 << 1)
#define UART_MODEM_OUT1 (1 << 2)
#define UART_MODEM_OUT2 (1 << 3)
#define UART_MODEM_LOOPBACK (1 << 4)

#define UART_INTERRUPT_WHEN_DATA_AVAILABLE (1 << 0)
#define UART_INTERRUPT_WHEN_TRANSMITTER_EMPTY (1 << 1)
#define UART_INTERRUPT_WHEN_BREAK_EMPTY (1 << 2)
#define UART_INTERRUPT_WHEN_STATUS_UPDATE (1 << 3)

#define UART_LINE_DATA_READY (1 << 0)
#define UART_LINE_OVERRUN_ERROR (1 << 1)
#define UART_LINE_PARITY_ERROR (1 << 2)
#define UART_LINE_FRAMING_ERROR (1 << 3)
#define UART_LINE_BREAK_INDICATOR (1 << 4)
#define UART_LINE_TRANSMITTER_BUF_EMPTY (1 << 5)
#define UART_LINE_TRANSMITTER_EMPTY (1 << 6)
#define UART_LINE_IMPENDING_ERROR (1 << 7)

#define UART_ENABLE_FIFO (1 << 0)
#define UART_FIFO_CLEAR_RECEIVE (1 << 1)
#define UART_FIFO_CLEAR_TRANSMIT (1 << 2)
#define UART_FIFO_ENABLE_64_BYTE (1 << 5)
#define UART_FIFO_TRIGGER_LEVEL1 (0 << 6)
#define UART_FIFO_TRIGGER_LEVEL2 (1 << 6)
#define UART_FIFO_TRIGGER_LEVEL3 (2 << 6)
#define UART_FIFO_TRIGGER_LEVEL4 (3 << 6)

#endif // DRIVERS_UART_UART_DEFS_H